export default [
    {
        id: 1,
        name: "Pixie",
        size: "Tiny",
        type: "fey",
        align: "neutral good",
        AC:"15",
        HP: "1",
        STR: "2",
        DEX: "20",
        CON: "8",
        INT: "10",
        WIS: "14",
        CHA: "15",
        desc: "",
    },
    {
        id: 2,
        name: "Sprite",
        size: "Tiny",
        type: "fey",
        align: "neutral good",
        AC:"15",
        HP: "2",
        STR: "3",
        DEX: "18",
        CON: "10",
        INT: "14",
        WIS: "13",
        CHA: "11",
        desc: "",
    },
    {
        id: 3,
        name: "Tiny servant",
        size: "Tiny",
        type: "construct",
        align: "",
        AC:"15",
        HP: "10",
        STR: "4",
        DEX: "16",
        CON: "10",
        INT: "2",
        WIS: "10",
        CHA: "1",
        desc: "",
    },
]