export default [
    {
        id: 1,
        name: "Fireball",
        level: 3,
        casting_time: "1 ation",
        range: "150ft",
        component:"V, S, M (a ball of bat guano and sulfur)",
        duration: "Instantaneous",
        school: "Evocation",
        attack: "DEX save",
        damage: "Fire",
        description: "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one. The fire spreads around corners. It ignites flammable objects in the area that aren't being worn or carried.",
        available: "Sorcerer, Wizard",
    },
    {
        id: 2,
        name: "Faerie Fire",
        level: 1,
        casting_time: "1 action",
        range: "60ft",
        component:"V",
        duration: "1 minute",
        school: "Evocation",
        attack: "DEX save",
        damage: "Debuff",
        description: "Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius. Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can't benefit from being invisible.",
        available: "Bard, Druid",
    },
    {
        id: 3,
        name: "Delayed Blast Fireball",
        level: 7,
        casting_time: "1 action",
        range: "150ft",
        component:" V, S, M (a ball of bat guano and sulfur)",
        duration: "1 minute",
        school: "Evocation",
        attack: "DEX save",
        damage: "Fire",
        description: "A beam of yellow light flashes from your pointing finger, then condenses to linger at a chosen point within range as a glowing bead for the duration. When the spell ends, either because your concentration is broken or because you decide to end it, the bead blossoms with a low roar into an explosion of flame that spreads around corners. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A creature takes fire damage equal to the total accumulated damage on a failed save, or half as much damage on a successful one. The spell's base damage is 12d6. If at the end of your turn the bead has not yet detonated, the damage increases by 1d6. If the glowing bead is touched before the interval has expired, the creature touching it must make a Dexterity saving throw. On a failed save, the spell ends immediately, causing the bead to erupt in flame. On a successful save, the creature can throw the bead up to 40 feet. When it strikes a creature or a solid object, the spell ends, and the bead explodes. The fire damages objects in the area and ignites flammable objects that aren't being worn or carried.",
        available: "Sorcerer, Wizard",
    },
]